# Generated by Django 3.2.3 on 2021-05-24 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='realtors',
            new_name='realtor',
        ),
    ]
